### PR TITLE
Set up PostgreSQL server with Docker

### PR DESCRIPTION
**Pull request by chapwiz**
Created .yml file for Docker container implementation for PostgreSQL.

### CODE REVIEW

**Review by melvillewong — DISMISSED** [review]
Is there a data/ to ignore?

**Comment by chapwiz** [comment]
> Is there a data/ to ignore?

Just trying to setup Docker to have a successful implementation with PostgreSQL, and docker-compose.yml is essential. Thank you for the kind review

**Review by melvillewong — DISMISSED** [review]
LGTM

**Review by melvillewong — APPROVED** [review]
Very good!

**Pull request merged**
